// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Locomotiv.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251215233732_AjoutStationIdDansEtape")]
    partial class AjoutStationIdDansEtape
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.28");

            modelBuilder.Entity("Locomotiv.Model.Block", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstOccupe")
                        .HasColumnType("INTEGER");

                    b.Property<double>("LatitudeArrivee")
                        .HasColumnType("REAL");

                    b.Property<double>("LatitudeDepart")
                        .HasColumnType("REAL");

                    b.Property<double>("LongitudeArrivee")
                        .HasColumnType("REAL");

                    b.Property<double>("LongitudeDepart")
                        .HasColumnType("REAL");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Signal")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TrainId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VoieId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TrainId");

                    b.HasIndex("VoieId");

                    b.ToTable("Blocks");
                });

            modelBuilder.Entity("Locomotiv.Model.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateReservation")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItineraireId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NombrePlaces")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<decimal>("PrixTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Confirmé");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DateReservation");

                    b.HasIndex("ItineraireId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Locomotiv.Model.Etape", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BlockId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("HeureArrivee")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("HeureDepart")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ItineraireId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lieu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordre")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrainId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BlockId");

                    b.HasIndex("ItineraireId");

                    b.HasIndex("StationId");

                    b.HasIndex("TrainId");

                    b.ToTable("Etapes");
                });

            modelBuilder.Entity("Locomotiv.Model.Itineraire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateArrivee")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateDepart")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TrainId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TrainId")
                        .IsUnique();

                    b.ToTable("Itineraires");
                });

            modelBuilder.Entity("Locomotiv.Model.PointArret", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstStation")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Localisation")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PointArrets");
                });

            modelBuilder.Entity("Locomotiv.Model.Signal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstActif")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.ToTable("Signaux");
                });

            modelBuilder.Entity("Locomotiv.Model.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CapaciteMaxTrains")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Localisation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("StationType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("Locomotiv.Model.Train", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BlockId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacite")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Etat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("StationId")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BlockId");

                    b.HasIndex("StationId");

                    b.ToTable("Trains");
                });

            modelBuilder.Entity("Locomotiv.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("StationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Locomotiv.Model.Voie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.ToTable("Voies");
                });

            modelBuilder.Entity("Locomotiv.Model.Block", b =>
                {
                    b.HasOne("Locomotiv.Model.Train", "Train")
                        .WithMany()
                        .HasForeignKey("TrainId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Locomotiv.Model.Voie", null)
                        .WithMany("Blocks")
                        .HasForeignKey("VoieId");

                    b.Navigation("Train");
                });

            modelBuilder.Entity("Locomotiv.Model.Booking", b =>
                {
                    b.HasOne("Locomotiv.Model.Itineraire", "Itineraire")
                        .WithMany()
                        .HasForeignKey("ItineraireId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Locomotiv.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Itineraire");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Locomotiv.Model.Etape", b =>
                {
                    b.HasOne("Locomotiv.Model.Block", "Block")
                        .WithMany()
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Locomotiv.Model.Itineraire", "Itineraire")
                        .WithMany("Etapes")
                        .HasForeignKey("ItineraireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Locomotiv.Model.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Locomotiv.Model.Train", "Train")
                        .WithMany("Etapes")
                        .HasForeignKey("TrainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Block");

                    b.Navigation("Itineraire");

                    b.Navigation("Station");

                    b.Navigation("Train");
                });

            modelBuilder.Entity("Locomotiv.Model.Itineraire", b =>
                {
                    b.HasOne("Locomotiv.Model.Train", "Train")
                        .WithOne("Itineraire")
                        .HasForeignKey("Locomotiv.Model.Itineraire", "TrainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Train");
                });

            modelBuilder.Entity("Locomotiv.Model.Signal", b =>
                {
                    b.HasOne("Locomotiv.Model.Station", "Station")
                        .WithMany("Signaux")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("Locomotiv.Model.Train", b =>
                {
                    b.HasOne("Locomotiv.Model.Block", "Block")
                        .WithMany()
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Locomotiv.Model.Station", "Station")
                        .WithMany("Train")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Block");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("Locomotiv.Model.User", b =>
                {
                    b.HasOne("Locomotiv.Model.Station", "Station")
                        .WithMany("Employes")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Station");
                });

            modelBuilder.Entity("Locomotiv.Model.Voie", b =>
                {
                    b.HasOne("Locomotiv.Model.Station", "Station")
                        .WithMany("Voies")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("Locomotiv.Model.Itineraire", b =>
                {
                    b.Navigation("Etapes");
                });

            modelBuilder.Entity("Locomotiv.Model.Station", b =>
                {
                    b.Navigation("Employes");

                    b.Navigation("Signaux");

                    b.Navigation("Train");

                    b.Navigation("Voies");
                });

            modelBuilder.Entity("Locomotiv.Model.Train", b =>
                {
                    b.Navigation("Etapes");

                    b.Navigation("Itineraire")
                        .IsRequired();
                });

            modelBuilder.Entity("Locomotiv.Model.Voie", b =>
                {
                    b.Navigation("Blocks");
                });
#pragma warning restore 612, 618
        }
    }
}
